spring.application.name=gateway
server.port=8080

#M1 - autenticacao
spring.cloud.gateway.server.webmvc.routes[0].id=autenticacao-usuarios
spring.cloud.gateway.server.webmvc.routes[0].uri=${M1}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/usuarios/**

spring.cloud.gateway.server.webmvc.routes[1].id=autenticacao-senha
spring.cloud.gateway.server.webmvc.routes[1].uri=${M1}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/senha/**

spring.cloud.gateway.server.webmvc.routes[2].id=autenticacao-auth
spring.cloud.gateway.server.webmvc.routes[2].uri=${M1}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/auth/**

#M2 - perfilcorrente
spring.cloud.gateway.server.webmvc.routes[3].id=perfilcorrente
spring.cloud.gateway.server.webmvc.routes[3].uri=${M2}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/perfilcorrente/**

#M3 - pagamentos
spring.cloud.gateway.server.webmvc.routes[4].id=pagamentos-payments
spring.cloud.gateway.server.webmvc.routes[4].uri=${M3}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/payments/**

spring.cloud.gateway.server.webmvc.routes[5].id=pagamentos-health
spring.cloud.gateway.server.webmvc.routes[5].uri=${M3}
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/health/**

#M4 - notificacoes
spring.cloud.gateway.server.webmvc.routes[6].id=notificacoes
spring.cloud.gateway.server.webmvc.routes[6].uri=${M4}
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/notificacoes/**

#M5 - investimentos
spring.cloud.gateway.server.webmvc.routes[7].id=investimentos-ordens
spring.cloud.gateway.server.webmvc.routes[7].uri=${M5}
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/ordens/**

spring.cloud.gateway.server.webmvc.routes[8].id=investimentos-cotacao
spring.cloud.gateway.server.webmvc.routes[8].uri=${M5}
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/cotacoes/**

spring.cloud.gateway.server.webmvc.routes[9].id=investimentos-carteira
spring.cloud.gateway.server.webmvc.routes[9].uri=${M5}
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/carteira/**

#M6 - cotacoes
spring.cloud.gateway.server.webmvc.routes[10].id=cotacoes
spring.cloud.gateway.server.webmvc.routes[10].uri=${M6}
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/api/cotacoestemporeal/**

#M7 - portifolio
spring.cloud.gateway.server.webmvc.routes[11].id=portifolio
spring.cloud.gateway.server.webmvc.routes[11].uri=${M7}
spring.cloud.gateway.server.webmvc.routes[11].predicates[0]=Path=/api/portifolio/**