spring.application.name=gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=autenticacao
spring.cloud.gateway.server.webmvc.routes[0].uri=${M1}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/autenticacao/**

spring.cloud.gateway.server.webmvc.routes[1].id=perfilcorrente
spring.cloud.gateway.server.webmvc.routes[1].uri=${M2}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/perfilcorrente/**

spring.cloud.gateway.server.webmvc.routes[2].id=pagamentos
spring.cloud.gateway.server.webmvc.routes[2].uri=${M3}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/pagamentos/**

spring.cloud.gateway.server.webmvc.routes[3].id=notificacoes
spring.cloud.gateway.server.webmvc.routes[3].uri=${M4}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/notificacoes/**

spring.cloud.gateway.server.webmvc.routes[4].id=investimentos
spring.cloud.gateway.server.webmvc.routes[4].uri=${M5}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/investimentos/**

spring.cloud.gateway.server.webmvc.routes[5].id=cotacoes
spring.cloud.gateway.server.webmvc.routes[5].uri=${M6}
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/cotacoes/**

spring.cloud.gateway.server.webmvc.routes[6].id=portifolio
spring.cloud.gateway.server.webmvc.routes[6].uri=${M7}
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/portifolio/**